//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_QuanLyResort_HQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachTaiKhoanKhachHang
    {
        public short MaTaiKhoan { get; set; }
        public string UserName { get; set; }
        public string Passwordd { get; set; }
        public Nullable<short> MaPQ { get; set; }
        public string TenPQ { get; set; }
    }
}
