//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_QuanLyResort_HQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatPhong()
        {
            this.PhieuXacNhanDatPhong1 = new HashSet<PhieuXacNhanDatPhong>();
        }
    
        public short MaDatPhong { get; set; }
        public short MaPhong { get; set; }
        public short MaPhuongThuc { get; set; }
        public Nullable<short> MaPhieuXacNhan { get; set; }
        public string TenKH { get; set; }
        public Nullable<System.DateTime> NgayDatPhong { get; set; }
        public Nullable<System.DateTime> NgayTraPhong { get; set; }
        public string YeuCauThem { get; set; }
    
        public virtual CheckInOut CheckInOut { get; set; }
        public virtual PhieuXacNhanDatPhong PhieuXacNhanDatPhong { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual PhuongThucThanhToan PhuongThucThanhToan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXacNhanDatPhong> PhieuXacNhanDatPhong1 { get; set; }
    }
}
