//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_QuanLyResort_HQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.TaiKhoan1 = new HashSet<TaiKhoan>();
        }
    
        public short MaKH { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public long SoCMND { get; set; }
        public int SDT { get; set; }
        public string QuocTich { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<short> MaTaiKhoan { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoan1 { get; set; }
    }
}
