//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_QuanLyResort_HQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHangNu
    {
        public short MaKH { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public long SoCMND { get; set; }
        public int SDT { get; set; }
        public string QuocTich { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<short> MaTaiKhoan { get; set; }
    }
}
