//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_QuanLyResort_HQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXacNhanDatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuXacNhanDatPhong()
        {
            this.DatPhong = new HashSet<DatPhong>();
        }
    
        public short MaPhieuXacNhan { get; set; }
        public short MaDatPhong { get; set; }
        public string TenKH { get; set; }
        public string YeuCauThem { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<System.DateTime> NgayDatPhong { get; set; }
        public Nullable<System.DateTime> NgayTraPhong { get; set; }
        public string TrangThaiDatPhong { get; set; }
        public short MaPhuongThuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong> DatPhong { get; set; }
        public virtual DatPhong DatPhong1 { get; set; }
        public virtual PhuongThucThanhToan PhuongThucThanhToan { get; set; }
    }
}
