//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_QuanLyResort_HQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeDoanhThu
    {
        public short MaThongKe { get; set; }
        public System.DateTime ThangThongKe { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string ChiTiet { get; set; }
        public short MaNV { get; set; }
        public Nullable<decimal> TongDoanhThu { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
