//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_QuanLyResort_HQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinNhanVien
    {
        public short MaNV { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public short MaChucVu { get; set; }
        public string TenChucVu { get; set; }
    }
}
