//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_QuanLyResort_HQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinDatPhong
    {
        public short MaDatPhong { get; set; }
        public string TenKH { get; set; }
        public short MaPhong { get; set; }
        public short MaLoai { get; set; }
        public string TenLoai { get; set; }
        public string MoTaThongTin { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string TenPhuongThuc { get; set; }
        public Nullable<System.DateTime> NgayDatPhong { get; set; }
        public Nullable<System.DateTime> NgayTraPhong { get; set; }
        public string YeuCauThem { get; set; }
    }
}
