//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_QuanLyResort_HQTCSDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TienIchResort
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TienIchResort()
        {
            this.DatTienIchResort = new HashSet<DatTienIchResort>();
        }
    
        public short MaTienIch { get; set; }
        public string TenTienIch { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatTienIchResort> DatTienIchResort { get; set; }
    }
}
